# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e089b74fc7fa6bbf22e7c6c2d9575c57543292f54127984b5f32d82afd0f742e9e3320dce6d1141704713196335039200ec07b35bc40d95151273f41c29cae70

test:
  secret_key_base: e357b14e0c63b182cbc679618bf5ff8c358469c29c48c165773bb1bf35ec1fd6cb47de78072decfec24b2ea57d7c919414eb9a3f57240ffa2a61d955e35d471a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
